version: 1

binary: vigiles
main: .
goos: linux
goarch: amd64

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

flags:
  - -trimpath

ldflags:
  - "-s -w -X github.com/apoorv-kulkarni/vigiles/cmd.Version={{ .Tag }}"
