version: 2

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

flags:
  - -trimpath

ldflags:
  - -s -w
  - -X github.com/apoorv-kulkarni/vigiles/cmd.Version={{ .Tag }}

goos:
  - linux
  - darwin
  - windows

goarch:
  - amd64
  - arm64

main: .
binary: vigiles
